[package]
name = "zap-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = { version = "3.17.0", features = ["collections"] }
slotmap = "1.0.7"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "eval"
harness = false
